import { setupNavigation } from "./components/nav.js";
import { setupDarkMode } from "./components/darkMode.js";
import { setupAccordion } from "./components/accordion.js";
import { setupLightbox } from "./components/lightbox.js";
import { setupScrollAnimations } from "./components/scrollAnimations.js";
import { setupBackToTop } from "./components/backToTop.js";
import { setupReadingProgress } from "./components/readingProgress.js";
import { setupContactFormValidation } from "./components/formValidator.js";
import { setupServicesAPI } from "./components/serviceApi.js";
import { setupTeamAPI } from "./components/teamApi.js";
import { setupHomeNewAPI } from "./components/homeNewApi.js";

setupNavigation();
setupDarkMode();
setupAccordion();
setupLightbox();
setupScrollAnimations();
setupBackToTop();
setupReadingProgress();
setupContactFormValidation();
setupServicesAPI();
setupTeamAPI();
setupHomeNewAPI();
